LOCATION=europe-west3\
  PROJECT_ID=qrmenu-act\
  ALGOLIA_APP_ID=\
  ALGOLIA_API_KEY=\
  ALGOLIA_INDEX_NAME=items\
  COLLECTION_PATH=items\
  FIELDS={}\
  TRANSFORM_FUNCTION={}\
  GOOGLE_APPLICATION_CREDENTIALS=""\
  npx firestore-algolia-search
